### ISSUE TITLE
this.getJhipsterAppConfig is not a function

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/generator-jhipster-module#52]
Steps to reproduce:

1. `npm -g install generator-jhipster-module`
2. `mkdir test && cd test`
3. `yo jhipster-module` # name the module "test"
4. `npm link`
5. `yo jhipster-test`

Here is the error:

```
yo jhipster-test
events.js:180
      throw er; // Unhandled 'error' event
      ^
TypeError: this.getJhipsterAppConfig is not a function
```

Replacing `this.getJhipsterAppConfig` by `this.getAllJhipsterConfig` solve the problem.

**Comment by fdelbrayelle** [comment]
Already fixed by https://github.com/jhipster/generator-jhipster-module/commit/cfa70176a2c1e86eb2e75c2c8750ae2d8559b9bf but last npm release was made before (v2.5.0).

**Comment by fdelbrayelle** [comment]
When trying to generate a new module after linking by `npm link` the generator-jhipster-module there is another error where `this.getAllJhipsterConfig` appears to be in cause:

```
yo jhipster-kafka
events.js:180
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'blueprints' of undefined
    at loadBlueprintsFromConfiguration (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/generators/utils.js:565:38)                                                          
    at Object.getAllJhipsterConfig (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/generators/utils.js:504:36)                                                              
    at module.exports.getAllJhipsterConfig (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/generators/generator-base.js:2060:30)                                            
    at module.exports.readConfig (/home/francois/dev/jhipster/generator-jhipster-kafka/generators/app/index.js:16:47)                                                                                             
    at Object.<anonymous> (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)                                                
    at /home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/run-async/index.js:24:19
    at /home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13                                                                     
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event at:
    at Immediate.<anonymous> (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:433:22)                                             
    at processImmediate (internal/timers.js:439:21)
```

**Comment by fdelbrayelle** [comment]
False alarm: there is no issue when lauching `yo jhipster-kafka` in a brand new sample test project :)

Thank you @pascalgrimaud ! I'm closing this one.
